name: Run Terminal Command

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a terminal command
        run: |
          curl ascii.live/parrot
          ls -alh
